/* =========================================================================
   ЗАКЛЯТТЯ — шар даних (404 шт.)

   Довідник: назва, рівень, школа, класи, час чаклування, ритуал, концентрація
   і джерело. Описів тут немає навмисне — вони роздули б файл учетверо (чотири
   мови), а для вибору заклять і запису в чарник досить назв.

   Поля: uk — українська назва (канон, нею працює решта коду), en — оригінал
   для звірки, lvl 0 = замовляння, cls — класи зі списком цього закляття
   (Таємний трюкач і Лицар-маг беруть зі списку Чарівника), src — джерело
   (див. SPELL_SOURCES), only24 — закляття, якого в правилах 2014 не існує.

   Джерела механіки: System Reference Document 5.1 і 5.2 © Wizards of the Coast
   LLC, ліцензія Creative Commons Attribution 4.0 International (CC-BY-4.0).
   Закляття з PHB/XGE/TCE — лише механічні факти (рівень, школа, класи, час) і
   наші назви; текстів заклять із цих книжок ми не переносимо.
   Українські назви — наш переклад; звірка й правки — у SPELLS.md.
   ========================================================================= */
(function () {
  "use strict";

  // Школи магії: наша назва (як пишемо в тексті «зі школи …») → оригінал
  window.SPELL_SCHOOLS = {
      "ограждення": "Abjuration",
      "прикликання": "Conjuration",
      "віщування": "Divination",
      "зачарування": "Enchantment",
      "викликання": "Evocation",
      "ілюзії": "Illusion",
      "некромантія": "Necromancy",
      "перетворення": "Transmutation"
  };

  /* Джерела. def — чи ввімкнене за замовчуванням; користувач зможе вимкнути
     те, чого немає за його столом (напр. лишити самий PHB). */
  window.SPELL_SOURCES = [
    { id:"srd", uk:"SRD 5.1 — база", def:true },
    { id:"srd24", uk:"SRD 5.2 — додане 2024-м", def:true },
    { id:"phb", uk:"PHB — поза SRD", def:true },
    { id:"xge", uk:"Xanathar's Guide", def:true },
    { id:"tce", uk:"Tasha's Cauldron", def:true },
  ];

  // Поточний фільтр: усі джерела ввімкнені, суто 2024-ві закляття — ні,
  // бо апка рахує персонажа за правилами 2014 року.
  window.SPELL_FILTER = { srd: true, srd24: true, phb: true, xge: true, tce: true, ed2024: false };

  window.SPELLS = [
    // --- замовляння (0 рівень) ---
    { uk:"Вогняна стріла", en:"Fire Bolt", lvl:0, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Гримуче лезо", en:"Booming Blade", lvl:0, school:"викликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Громовий ляск", en:"Thunderclap", lvl:0, school:"викликання", cls:["Бард","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Друзі", en:"Friends", lvl:0, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"phb", conc:true },
    { uk:"Друїдство", en:"Druidcraft", lvl:0, school:"перетворення", cls:["Друїд"], cast:"дія", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Дубець", en:"Shillelagh", lvl:0, school:"перетворення", cls:["Друїд"], cast:"бонусна дія", src:"srd", rng:"Дотик", dur:"1 хв", comp:"В·С·М" },
    { uk:"Електрична приманка", en:"Lightning Lure", lvl:0, school:"викликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Електричний дотик", en:"Shocking Grasp", lvl:0, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С" },
    { uk:"Захист від клинків", en:"Blade Ward", lvl:0, school:"ограждення", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"phb" },
    { uk:"Зеленополумʼяне лезо", en:"Green-Flame Blade", lvl:0, school:"викликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Злісні насмішки", en:"Vicious Mockery", lvl:0, school:"зачарування", cls:["Бард"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Зоряний вогник", en:"Starry Wisp", lvl:0, school:"викликання", cls:["Бард","Друїд"], cast:"дія", src:"srd24", rng:"60 фт", dur:"Миттєво", comp:"В·С", only24:true },
    { uk:"Керування полумʼям", en:"Control Flames", lvl:0, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Кислотні бризки", en:"Acid Splash", lvl:0, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Лагодження", en:"Mending", lvl:0, school:"перетворення", cls:["Клірик","Бард","Друїд","Чаклун","Чарівник"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Мала ілюзія", en:"Minor Illusion", lvl:0, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 хв", comp:"С·М" },
    { uk:"Містичний вибух", en:"Eldritch Blast", lvl:0, school:"викликання", cls:["Чорнокнижник"], cast:"дія", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Навала паразитів", en:"Infestation", lvl:0, school:"прикликання", cls:["Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Настанова", en:"Guidance", lvl:0, school:"віщування", cls:["Клірик","Друїд"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Обмороження", en:"Frostbite", lvl:0, school:"викликання", cls:["Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Опір", en:"Resistance", lvl:0, school:"ограждення", cls:["Клірик","Друїд"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Отруйні бризки", en:"Poison Spray", lvl:0, school:"прикликання", cls:["Чаклун","Чорнокнижник","Чарівник","Друїд"], cast:"дія", src:"srd", rng:"10 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Первісна лють", en:"Primal Savagery", lvl:0, school:"перетворення", cls:["Друїд"], cast:"дія", src:"xge" },
    { uk:"Подзвін по мертвих", en:"Toll the Dead", lvl:0, school:"некромантія", cls:["Клірик","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Порив", en:"Gust", lvl:0, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Порятунок помираючого", en:"Spare the Dying", lvl:0, school:"некромантія", cls:["Клірик"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С" },
    { uk:"Послання", en:"Message", lvl:0, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"1 раунд", comp:"В·С·М" },
    { uk:"Промінь холоду", en:"Ray of Frost", lvl:0, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Рука мага", en:"Mage Hand", lvl:0, school:"прикликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 хв", comp:"В·С" },
    { uk:"Священне полум'я", en:"Sacred Flame", lvl:0, school:"викликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Світло", en:"Light", lvl:0, school:"викликання", cls:["Бард","Клірик","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·М" },
    { uk:"Слово сяйва", en:"Word of Radiance", lvl:0, school:"викликання", cls:["Клірик"], cast:"дія", src:"xge" },
    { uk:"Сплеск клинків", en:"Sword Burst", lvl:0, school:"прикликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Створення багаття", en:"Create Bonfire", lvl:0, school:"прикликання", cls:["Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge", conc:true },
    { uk:"Створення полум'я", en:"Produce Flame", lvl:0, school:"прикликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"На себе", dur:"10 хв", comp:"В·С" },
    { uk:"Стихійництво", en:"Elementalism", lvl:0, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd24", rng:"30 фт", dur:"Миттєво", comp:"В·С", only24:true },
    { uk:"Тавматургія", en:"Thaumaturgy", lvl:0, school:"перетворення", cls:["Клірик"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 хв", comp:"В" },
    { uk:"Танцюючі вогники", en:"Dancing Lights", lvl:0, school:"викликання", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Терновий батіг", en:"Thorn Whip", lvl:0, school:"перетворення", cls:["Друїд"], cast:"дія", src:"phb" },
    { uk:"Точний удар", en:"True Strike", lvl:0, school:"віщування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 раунд", comp:"С", conc:true },
    { uk:"Уламок розуму", en:"Mind Sliver", lvl:0, school:"зачарування", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"tce" },
    { uk:"Фокуси", en:"Prestidigitation", lvl:0, school:"перетворення", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"10 фт", dur:"1 год", comp:"В·С" },
    { uk:"Формування води", en:"Shape Water", lvl:0, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Формування землі", en:"Mold Earth", lvl:0, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Холодний дотик", en:"Chill Touch", lvl:0, school:"некромантія", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"1 раунд", comp:"В·С" },
    { uk:"Чаклунський сплеск", en:"Sorcerous Burst", lvl:0, school:"викликання", cls:["Чаклун"], cast:"дія", src:"srd24", rng:"120 фт", dur:"Миттєво", only24:true },
    { uk:"Чарівний камінь", en:"Magic Stone", lvl:0, school:"перетворення", cls:["Друїд","Чорнокнижник"], cast:"бонусна дія", src:"xge" },
    // --- 1 рівень ---
    { uk:"Ілюзорний напис", en:"Illusory Script", lvl:1, school:"ілюзії", cls:["Бард","Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"10 дн.", comp:"С·М", ritual:true },
    { uk:"Їдке вариво Таші", en:"Tasha's Caustic Brew", lvl:1, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Барвисті бризки", en:"Color Spray", lvl:1, school:"ілюзії", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 раунд", comp:"В·С·М" },
    { uk:"Безмовний образ", en:"Silent Image", lvl:1, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Благословення", en:"Bless", lvl:1, school:"зачарування", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Божественна прихильність", en:"Divine Favor", lvl:1, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Броня Агатиса", en:"Armor of Agathys", lvl:1, school:"ограждення", cls:["Чорнокнижник"], cast:"дія", src:"phb" },
    { uk:"Броня мага", en:"Mage Armor", lvl:1, school:"ограждення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"8 год", comp:"В·С·М" },
    { uk:"Виявлення зла і добра", en:"Detect Evil and Good", lvl:1, school:"віщування", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Виявлення магії", en:"Detect Magic", lvl:1, school:"віщування", cls:["Бард","Клірик","Друїд","Паладин","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С", ritual:true, conc:true },
    { uk:"Виявлення отрути і хвороби", en:"Detect Poison and Disease", lvl:1, school:"віщування", cls:["Клірик","Друїд","Паладин","Слідопит"], cast:"дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С·М", ritual:true, conc:true },
    { uk:"Відьомський розряд", en:"Witch Bolt", lvl:1, school:"викликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"phb", conc:true },
    { uk:"Героїзм", en:"Heroism", lvl:1, school:"зачарування", cls:["Бард","Паладин"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Гнівний удар", en:"Wrathful Smite", lvl:1, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Град шипів", en:"Hail of Thorns", lvl:1, school:"прикликання", cls:["Слідопит"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Громова хвиля", en:"Thunderwave", lvl:1, school:"викликання", cls:["Бард","Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С" },
    { uk:"Громовий удар", en:"Thunderous Smite", lvl:1, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Дар жвавості", en:"Gift of Alacrity", lvl:1, school:"віщування", cls:["Чарівник"], cast:"1 хв", src:"tce" },
    { uk:"Дисонансний шепіт", en:"Dissonant Whispers", lvl:1, school:"зачарування", cls:["Бард"], cast:"дія", src:"srd24", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Довгий крок", en:"Longstrider", lvl:1, school:"перетворення", cls:["Бард","Друїд","Слідопит","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С·М" },
    { uk:"Дружба з тваринами", en:"Animal Friendship", lvl:1, school:"зачарування", cls:["Бард","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"30 фт", dur:"24 год", comp:"В·С·М" },
    { uk:"Заплутування", en:"Entangle", lvl:1, school:"прикликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"90 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Захист від зла і добра", en:"Protection from Evil and Good", lvl:1, school:"ограждення", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Зачарування особи", en:"Charm Person", lvl:1, school:"зачарування", cls:["Бард","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 год", comp:"В·С" },
    { uk:"Згуба", en:"Bane", lvl:1, school:"зачарування", cls:["Бард","Клірик"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Катапульта", en:"Catapult", lvl:1, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Крижаний ніж", en:"Ice Knife", lvl:1, school:"прикликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd24", rng:"60 фт", dur:"Миттєво", comp:"С·М" },
    { uk:"Летючий диск", en:"Floating Disk", lvl:1, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 год", comp:"В·С·М", ritual:true },
    { uk:"Лікування ран", en:"Cure Wounds", lvl:1, school:"викликання", cls:["Бард","Клірик","Друїд","Паладин","Слідопит"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С" },
    { uk:"Магічна стріла", en:"Magic Missile", lvl:1, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Маскування", en:"Disguise Self", lvl:1, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 год", comp:"В·С" },
    { uk:"Мастило", en:"Grease", lvl:1, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"1 хв", comp:"В·С·М" },
    { uk:"Мітка мисливця", en:"Hunter's Mark", lvl:1, school:"віщування", cls:["Слідопит"], cast:"бонусна дія", src:"srd", rng:"90 фт", dur:"До 1 год", comp:"В", conc:true },
    { uk:"Наказ", en:"Command", lvl:1, school:"зачарування", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"60 фт", dur:"1 раунд", comp:"В" },
    { uk:"Нанесення ран", en:"Inflict Wounds", lvl:1, school:"некромантія", cls:["Клірик"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С" },
    { uk:"Невидимий слуга", en:"Unseen Servant", lvl:1, school:"прикликання", cls:["Бард","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"1 год", comp:"В·С·М", ritual:true },
    { uk:"Несправжнє життя", en:"False Life", lvl:1, school:"некромантія", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 год", comp:"В·С·М" },
    { uk:"Нестримний регіт", en:"Hideous Laughter", lvl:1, school:"зачарування", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Очищення їжі та питва", en:"Purify Food and Drink", lvl:1, school:"перетворення", cls:["Клірик","Друїд","Паладин"], cast:"дія", src:"srd", rng:"10 фт", dur:"Миттєво", comp:"В·С", ritual:true },
    { uk:"Падіння пір'їнкою", en:"Feather Fall", lvl:1, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"реакція", src:"srd", rng:"60 фт", dur:"1 хв", comp:"В·М" },
    { uk:"Палаючі руки", en:"Burning Hands", lvl:1, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С" },
    { uk:"Пастковий удар", en:"Ensnaring Strike", lvl:1, school:"прикликання", cls:["Слідопит"], cast:"бонусна дія", src:"srd24", rng:"На себе", dur:"До 1 хв", comp:"В", conc:true },
    { uk:"Пекельний докір", en:"Hellish Rebuke", lvl:1, school:"викликання", cls:["Чорнокнижник"], cast:"реакція", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Пекучий удар", en:"Searing Smite", lvl:1, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"srd24", rng:"На себе", dur:"1 хв" },
    { uk:"Поглинання стихій", en:"Absorb Elements", lvl:1, school:"ограждення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"реакція", src:"xge" },
    { uk:"Пошук фамільяра", en:"Find Familiar", lvl:1, school:"прикликання", cls:["Чарівник"], cast:"1 год", src:"srd", rng:"10 фт", dur:"Миттєво", comp:"В·С·М", ritual:true },
    { uk:"Примусовий двобій", en:"Compelled Duel", lvl:1, school:"зачарування", cls:["Паладин"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Пристріт", en:"Hex", lvl:1, school:"зачарування", cls:["Чорнокнижник"], cast:"бонусна дія", src:"srd24", rng:"90 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Притулок", en:"Sanctuary", lvl:1, school:"ограждення", cls:["Клірик"], cast:"бонусна дія", src:"srd", rng:"30 фт", dur:"1 хв", comp:"В·С·М" },
    { uk:"Промінь хвороби", en:"Ray of Sickness", lvl:1, school:"некромантія", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd24", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Розмова з тваринами", en:"Speak with Animals", lvl:1, school:"віщування", cls:["Бард","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"На себе", dur:"10 хв", comp:"В·С", ritual:true },
    { uk:"Розпізнавання", en:"Identify", lvl:1, school:"віщування", cls:["Бард","Чарівник"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М", ritual:true },
    { uk:"Розуміння мов", en:"Comprehend Languages", lvl:1, school:"віщування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 год", comp:"В·С·М", ritual:true },
    { uk:"Руки Хадара", en:"Arms of Hadar", lvl:1, school:"прикликання", cls:["Чорнокнижник"], cast:"дія", src:"phb" },
    { uk:"Різнобарвна сфера", en:"Chromatic Orb", lvl:1, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd24", rng:"90 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Скерований промінь", en:"Guiding Bolt", lvl:1, school:"викликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"120 фт", dur:"1 раунд", comp:"В·С" },
    { uk:"Сон", en:"Sleep", lvl:1, school:"зачарування", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"90 фт", dur:"1 хв", comp:"В·С·М" },
    { uk:"Створення або знищення води", en:"Create or Destroy Water", lvl:1, school:"перетворення", cls:["Клірик","Друїд"], cast:"дія", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Стрибок", en:"Jump", lvl:1, school:"перетворення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 хв", comp:"В·С·М" },
    { uk:"Тривога", en:"Alarm", lvl:1, school:"ограждення", cls:["Слідопит","Чарівник"], cast:"1 хв", src:"srd", rng:"30 фт", dur:"8 год", comp:"В·С·М", ritual:true },
    { uk:"Удар зефіру", en:"Zephyr Strike", lvl:1, school:"перетворення", cls:["Слідопит"], cast:"бонусна дія", src:"xge", conc:true },
    { uk:"Хмара туману", en:"Fog Cloud", lvl:1, school:"прикликання", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Цілюща ягода", en:"Goodberry", lvl:1, school:"перетворення", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Цілюще слово", en:"Healing Word", lvl:1, school:"викликання", cls:["Бард","Клірик","Друїд"], cast:"бонусна дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Чарівний вогонь", en:"Faerie Fire", lvl:1, school:"викликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В", conc:true },
    { uk:"Швидкий відступ", en:"Expeditious Retreat", lvl:1, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"бонусна дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Щит", en:"Shield", lvl:1, school:"ограждення", cls:["Чаклун","Чарівник"], cast:"реакція", src:"srd", rng:"На себе", dur:"1 раунд", comp:"В·С" },
    { uk:"Щит віри", en:"Shield of Faith", lvl:1, school:"ограждення", cls:["Клірик","Паладин"], cast:"бонусна дія", src:"srd", rng:"60 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    // --- 2 рівень ---
    { uk:"Бачення невидимого", en:"See Invisibility", lvl:2, school:"віщування", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 год", comp:"В·С·М" },
    { uk:"Безслідний шлях", en:"Pass Without Trace", lvl:2, school:"ограждення", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Виявлення думок", en:"Detect Thoughts", lvl:2, school:"віщування", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Вогняна сфера", en:"Flaming Sphere", lvl:2, school:"прикликання", cls:["Друїд","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Вогняний клинок", en:"Flame Blade", lvl:2, school:"викликання", cls:["Друїд"], cast:"бонусна дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Ворожіння", en:"Augury", lvl:2, school:"віщування", cls:["Клірик"], cast:"1 хв", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С·М", ritual:true },
    { uk:"Відмикання", en:"Knock", lvl:2, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Вічне полум'я", en:"Continual Flame", lvl:2, school:"викликання", cls:["Клірик","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Дзеркальний образ", en:"Mirror Image", lvl:2, school:"ілюзії", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 хв", comp:"В·С" },
    { uk:"Допомога", en:"Aid", lvl:2, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"30 фт", dur:"8 год", comp:"В·С·М" },
    { uk:"Драконяче дихання", en:"Dragon's Breath", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"бонусна дія", src:"srd24", rng:"Дотик", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Дроблення", en:"Shatter", lvl:2, school:"викликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Духовна зброя", en:"Spiritual Weapon", lvl:2, school:"викликання", cls:["Клірик"], cast:"бонусна дія", src:"srd", rng:"60 фт", dur:"1 хв", comp:"В·С" },
    { uk:"Заворожування", en:"Enthrall", lvl:2, school:"зачарування", cls:["Бард","Чорнокнижник"], cast:"дія", src:"srd", rng:"60 фт", dur:"1 хв", comp:"В·С" },
    { uk:"Заспокоєння емоцій", en:"Calm Emotions", lvl:2, school:"зачарування", cls:["Бард","Клірик"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Захисні узи", en:"Warding Bond", lvl:2, school:"ограждення", cls:["Клірик"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С·М" },
    { uk:"Захист від отрути", en:"Protection from Poison", lvl:2, school:"ограждення", cls:["Клірик","Друїд","Паладин","Слідопит"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С" },
    { uk:"Збільшення/Зменшення", en:"Enlarge/Reduce", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Звірине чуття", en:"Beast Sense", lvl:2, school:"віщування", cls:["Друїд","Слідопит"], cast:"дія", src:"phb", ritual:true, conc:true },
    { uk:"Згасання і цвітіння", en:"Wither and Bloom", lvl:2, school:"некромантія", cls:["Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"tce" },
    { uk:"Зміна себе", en:"Alter Self", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Зона правди", en:"Zone of Truth", lvl:2, school:"зачарування", cls:["Бард","Клірик","Паладин"], cast:"дія", src:"srd", rng:"60 фт", dur:"10 хв", comp:"В·С" },
    { uk:"Кислотна стріла", en:"Acid Arrow", lvl:2, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"90 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Кора", en:"Barkskin", lvl:2, school:"перетворення", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Кордон стріл", en:"Cordon of Arrows", lvl:2, school:"перетворення", cls:["Слідопит"], cast:"1 хв", src:"phb" },
    { uk:"Корона безумства", en:"Crown of Madness", lvl:2, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"phb", conc:true },
    { uk:"Левітація", en:"Levitate", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Магічна аура арканіста", en:"Arcanist's Magic Aura", lvl:2, school:"ілюзії", cls:["Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"24 год", comp:"В·С·М" },
    { uk:"Магічна зброя", en:"Magic Weapon", lvl:2, school:"перетворення", cls:["Паладин","Чарівник"], cast:"бонусна дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Магічний замок", en:"Arcane Lock", lvl:2, school:"ограждення", cls:["Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Мале відновлення", en:"Lesser Restoration", lvl:2, school:"ограждення", cls:["Бард","Клірик","Друїд","Паладин","Слідопит"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С" },
    { uk:"Молитва зцілення", en:"Prayer of Healing", lvl:2, school:"викликання", cls:["Клірик"], cast:"10 хв", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В" },
    { uk:"Місячний промінь", en:"Moonbeam", lvl:2, school:"викликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Навіювання", en:"Suggestion", lvl:2, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 8 год", comp:"В·М", conc:true },
    { uk:"Невидимість", en:"Invisibility", lvl:2, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Павутина", en:"Web", lvl:2, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Павуче лазіння", en:"Spider Climb", lvl:2, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Палючий промінь", en:"Scorching Ray", lvl:2, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Порив вітру", en:"Gust of Wind", lvl:2, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Посилення характеристики", en:"Enhance Ability", lvl:2, school:"перетворення", cls:["Бард","Клірик","Друїд","Чаклун"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Пошук пасток", en:"Find Traps", lvl:2, school:"віщування", cls:["Клірик","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Пошук предмета", en:"Locate Object", lvl:2, school:"віщування", cls:["Бард","Клірик","Друїд","Паладин","Слідопит","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Пошук скакуна", en:"Find Steed", lvl:2, school:"прикликання", cls:["Паладин"], cast:"10 хв", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Пошук тварин або рослин", en:"Locate Animals or Plants", lvl:2, school:"віщування", cls:["Бард","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С·М", ritual:true },
    { uk:"Призов звіра", en:"Summon Beast", lvl:2, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", src:"tce", conc:true },
    { uk:"Примарна сила", en:"Phantasmal Force", lvl:2, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd24", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Промінь знесилення", en:"Ray of Enfeeblement", lvl:2, school:"некромантія", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Розжарення металу", en:"Heat Metal", lvl:2, school:"перетворення", cls:["Бард","Друїд"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Розмитість", en:"Blur", lvl:2, school:"ілюзії", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В", conc:true },
    { uk:"Сліпота/Глухота", en:"Blindness/Deafness", lvl:2, school:"некромантія", cls:["Бард","Клірик","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 хв", comp:"В" },
    { uk:"Спокійний спочинок", en:"Gentle Repose", lvl:2, school:"некромантія", cls:["Клірик","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"10 дн.", comp:"В·С·М", ritual:true },
    { uk:"Тавруючий удар", en:"Branding Smite", lvl:2, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В", conc:true },
    { uk:"Тварина-посланець", en:"Animal Messenger", lvl:2, school:"зачарування", cls:["Бард","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"30 фт", dur:"24 год", comp:"В·С·М", ritual:true },
    { uk:"Темнобачення", en:"Darkvision", lvl:2, school:"перетворення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"8 год", comp:"В·С·М" },
    { uk:"Темрява", en:"Darkness", lvl:2, school:"викликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 10 хв", comp:"В·М", conc:true },
    { uk:"Тиша", en:"Silence", lvl:2, school:"ілюзії", cls:["Бард","Клірик","Слідопит"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С", ritual:true, conc:true },
    { uk:"Трюк з мотузкою", en:"Rope Trick", lvl:2, school:"перетворення", cls:["Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С·М" },
    { uk:"Туманний крок", en:"Misty Step", lvl:2, school:"прикликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"бонусна дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В" },
    { uk:"Тіньовий клинок", en:"Shadow Blade", lvl:2, school:"ілюзії", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"бонусна дія", src:"xge", conc:true },
    { uk:"Утримання особи", en:"Hold Person", lvl:2, school:"зачарування", cls:["Бард","Клірик","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Хмара кинджалів", en:"Cloud of Daggers", lvl:2, school:"прикликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"phb", conc:true },
    { uk:"Чарівні вуста", en:"Magic Mouth", lvl:2, school:"ілюзії", cls:["Бард","Чарівник"], cast:"1 хв", src:"srd", rng:"30 фт", dur:"Доки не розсіють", comp:"В·С·М", ritual:true },
    { uk:"Шип розуму", en:"Mind Spike", lvl:2, school:"віщування", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd24", rng:"120 фт", dur:"До 1 год", comp:"С", conc:true },
    { uk:"Шипи", en:"Spike Growth", lvl:2, school:"перетворення", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"150 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    // --- 3 рівень ---
    { uk:"Блискавична стріла", en:"Lightning Arrow", lvl:3, school:"перетворення", cls:["Слідопит"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Блискавка", en:"Lightning Bolt", lvl:3, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Вампірський дотик", en:"Vampiric Touch", lvl:3, school:"некромантія", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Великий образ", en:"Major Image", lvl:3, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Виклик блискавки", en:"Call Lightning", lvl:3, school:"прикликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Вогняна куля", en:"Fireball", lvl:3, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Водне дихання", en:"Water Breathing", lvl:3, school:"перетворення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"24 год", comp:"В·С·М", ritual:true },
    { uk:"Вістка", en:"Sending", lvl:3, school:"викликання", cls:["Бард","Клірик","Чарівник"], cast:"дія", src:"srd", rng:"Необмежена", dur:"1 раунд", comp:"В·С·М" },
    { uk:"Газоподібна форма", en:"Gaseous Form", lvl:3, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Гіпнотичний візерунок", en:"Hypnotic Pattern", lvl:3, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"С·М", conc:true },
    { uk:"Денне світло", en:"Daylight", lvl:3, school:"викликання", cls:["Клірик","Друїд","Паладин","Слідопит","Чаклун"], cast:"дія", src:"srd", rng:"60 фт", dur:"1 год", comp:"В·С" },
    { uk:"Духи-охоронці", en:"Spirit Guardians", lvl:3, school:"прикликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Засліплюючий удар", en:"Blinding Smite", lvl:3, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Захист від стихій", en:"Protection From Energy", lvl:3, school:"ограждення", cls:["Клірик","Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Злиття з каменем", en:"Meld Into Stone", lvl:3, school:"перетворення", cls:["Клірик"], cast:"дія", src:"srd", rng:"Дотик", dur:"8 год", comp:"В·С", ritual:true },
    { uk:"Зняття прокляття", en:"Remove Curse", lvl:3, school:"ограждення", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С" },
    { uk:"Контрзакляття", en:"Counterspell", lvl:3, school:"ограждення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"реакція", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"С" },
    { uk:"Крижана буря", en:"Sleet Storm", lvl:3, school:"прикликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Магічне коло", en:"Magic Circle", lvl:3, school:"ограждення", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"10 фт", dur:"1 год", comp:"В·С·М" },
    { uk:"Маленька хатина", en:"Tiny Hut", lvl:3, school:"викликання", cls:["Бард","Чарівник"], cast:"1 хв", src:"srd", rng:"На себе", dur:"8 год", comp:"В·С·М", ritual:true },
    { uk:"Мантія хрестоносця", en:"Crusader's Mantle", lvl:3, school:"викликання", cls:["Паладин"], cast:"дія", src:"phb", conc:true },
    { uk:"Масове цілюще слово", en:"Mass Healing Word", lvl:3, school:"викликання", cls:["Клірик"], cast:"бонусна дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Маяк надії", en:"Beacon of Hope", lvl:3, school:"ограждення", cls:["Клірик"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Мерехтіння", en:"Blink", lvl:3, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 хв", comp:"В·С" },
    { uk:"Мови", en:"Tongues", lvl:3, school:"віщування", cls:["Бард","Клірик","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·М" },
    { uk:"Накладення прокляття", en:"Bestow Curse", lvl:3, school:"некромантія", cls:["Бард","Клірик","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Невиявність", en:"Nondetection", lvl:3, school:"ограждення", cls:["Бард","Слідопит","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"8 год", comp:"В·С·М" },
    { uk:"Оживлення мертвих", en:"Animate Dead", lvl:3, school:"некромантія", cls:["Клірик","Чарівник"], cast:"1 хв", src:"srd", rng:"10 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Охоронний гліф", en:"Glyph of Warding", lvl:3, school:"ограждення", cls:["Бард","Клірик","Чарівник"], cast:"1 год", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Пелена духів", en:"Spirit Shroud", lvl:3, school:"некромантія", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"бонусна дія", src:"tce", conc:true },
    { uk:"Повернення до життя", en:"Revivify", lvl:3, school:"прикликання", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Політ", en:"Fly", lvl:3, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Призов нежиті", en:"Summon Undead", lvl:3, school:"некромантія", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Призов тіньового поріддя", en:"Summon Shadowspawn", lvl:3, school:"прикликання", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Призов феї", en:"Summon Fey", lvl:3, school:"прикликання", cls:["Друїд","Слідопит","Чорнокнижник","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Прикликання залпу", en:"Conjure Barrage", lvl:3, school:"прикликання", cls:["Слідопит"], cast:"дія", src:"phb" },
    { uk:"Прикликання тварин", en:"Conjure Animals", lvl:3, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Примарний скакун", en:"Phantom Steed", lvl:3, school:"ілюзії", cls:["Чарівник"], cast:"1 хв", src:"srd", rng:"30 фт", dur:"1 год", comp:"В·С", ritual:true },
    { uk:"Пришвидшення", en:"Haste", lvl:3, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Розмова з мертвими", en:"Speak with Dead", lvl:3, school:"некромантія", cls:["Бард","Клірик"], cast:"дія", src:"srd", rng:"10 фт", dur:"10 хв", comp:"В·С·М" },
    { uk:"Розмова з рослинами", en:"Speak with Plants", lvl:3, school:"перетворення", cls:["Бард","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"На себе", dur:"10 хв", comp:"В·С" },
    { uk:"Розсіювання магії", en:"Dispel Magic", lvl:3, school:"ограждення", cls:["Бард","Клірик","Друїд","Паладин","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Ріст рослин", en:"Plant Growth", lvl:3, school:"перетворення", cls:["Бард","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Смердюча хмара", en:"Stinking Cloud", lvl:3, school:"прикликання", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"90 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Сповільнення", en:"Slow", lvl:3, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Створення їжі та води", en:"Create Food and Water", lvl:3, school:"прикликання", cls:["Клірик","Друїд","Паладин"], cast:"дія", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Стихійна зброя", en:"Elemental Weapon", lvl:3, school:"перетворення", cls:["Паладин"], cast:"дія", src:"phb", conc:true },
    { uk:"Страх", en:"Fear", lvl:3, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Стіна вітру", en:"Wind Wall", lvl:3, school:"викликання", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Фортеця інтелекту", en:"Intellect Fortress", lvl:3, school:"ограждення", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Ходіння по воді", en:"Water Walk", lvl:3, school:"перетворення", cls:["Клірик","Друїд","Слідопит","Чаклун"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 год", comp:"В·С·М", ritual:true },
    { uk:"Цілющий дух", en:"Healing Spirit", lvl:3, school:"прикликання", cls:["Друїд","Слідопит"], cast:"бонусна дія", src:"xge", conc:true },
    { uk:"Ясновидіння", en:"Clairvoyance", lvl:3, school:"віщування", cls:["Бард","Клірик","Чаклун","Чарівник"], cast:"10 хв", src:"srd", rng:"1 миля", dur:"До 10 хв", comp:"В·С·М", conc:true },
    // --- 4 рівень ---
    { uk:"Ілюзорна місцевість", en:"Hallucinatory Terrain", lvl:4, school:"ілюзії", cls:["Бард","Друїд","Чорнокнижник","Чарівник"], cast:"10 хв", src:"srd", rng:"300 фт", dur:"24 год", comp:"В·С·М" },
    { uk:"Їдка сфера", en:"Vitriolic Sphere", lvl:4, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd24", rng:"150 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Аура життя", en:"Aura of Life", lvl:4, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія", src:"srd24", rng:"На себе", dur:"До 10 хв", comp:"В", conc:true },
    { uk:"Аура чистоти", en:"Aura of Purity", lvl:4, school:"ограждення", cls:["Паладин"], cast:"дія", src:"phb", conc:true },
    { uk:"Вартовий віри", en:"Guardian of Faith", lvl:4, school:"прикликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"30 фт", dur:"8 год", comp:"В" },
    { uk:"Вигнання", en:"Banishment", lvl:4, school:"ограждення", cls:["Клірик","Паладин","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Виготовлення", en:"Fabricate", lvl:4, school:"перетворення", cls:["Чарівник"], cast:"10 хв", src:"srd", rng:"120 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Вища невидимість", en:"Greater Invisibility", lvl:4, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Вогняна стіна", en:"Wall of Fire", lvl:4, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Вогняний щит", en:"Fire Shield", lvl:4, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"10 хв", comp:"В·С·М" },
    { uk:"Вірний пес", en:"Faithful Hound", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"8 год", comp:"В·С·М" },
    { uk:"Гігантська комаха", en:"Giant Insect", lvl:4, school:"перетворення", cls:["Друїд"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Зачарування чудовиська", en:"Charm Monster", lvl:4, school:"зачарування", cls:["Бард","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd24", rng:"30 фт", dur:"1 год", comp:"В·С" },
    { uk:"Кам'яна шкіра", en:"Stoneskin", lvl:4, school:"ограждення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Керування водою", en:"Control Water", lvl:4, school:"перетворення", cls:["Клірик","Друїд","Чарівник"], cast:"дія", src:"srd", rng:"300 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Крижаний шторм", en:"Ice Storm", lvl:4, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"300 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Магічне око", en:"Arcane Eye", lvl:4, school:"віщування", cls:["Клірик","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Непробивна сфера", en:"Resilient Sphere", lvl:4, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Оберіг від смерті", en:"Death Ward", lvl:4, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"Дотик", dur:"8 год", comp:"В·С" },
    { uk:"Перевтілення", en:"Polymorph", lvl:4, school:"перетворення", cls:["Бард","Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Пошук істоти", en:"Locate Creature", lvl:4, school:"віщування", cls:["Бард","Клірик","Друїд","Паладин","Слідопит","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Приватне святилище", en:"Private Sanctum", lvl:4, school:"ограждення", cls:["Чарівник"], cast:"10 хв", src:"srd", rng:"120 фт", dur:"24 год", comp:"В·С·М" },
    { uk:"Приголомшливий удар", en:"Staggering Smite", lvl:4, school:"викликання", cls:["Паладин"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Призов аберації", en:"Summon Aberration", lvl:4, school:"прикликання", cls:["Друїд","Чорнокнижник","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Призов елементаля", en:"Summon Elemental", lvl:4, school:"прикликання", cls:["Друїд","Слідопит","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Призов конструкта", en:"Summon Construct", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Прикликання лісових створінь", en:"Conjure Woodland Beings", lvl:4, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Прикликання малих елементалів", en:"Conjure Minor Elementals", lvl:4, school:"прикликання", cls:["Друїд","Чарівник"], cast:"1 хв", src:"srd", rng:"90 фт", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Примарний убивця", en:"Phantasmal Killer", lvl:4, school:"ілюзії", cls:["Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Примус", en:"Compulsion", lvl:4, school:"зачарування", cls:["Бард"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Провидіння", en:"Divination", lvl:4, school:"віщування", cls:["Друїд"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С·М", ritual:true },
    { uk:"Просторові двері", en:"Dimension Door", lvl:4, school:"прикликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"500 фт", dur:"Миттєво", comp:"В" },
    { uk:"Підкорення звіра", en:"Dominate Beast", lvl:4, school:"зачарування", cls:["Друїд","Чаклун"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Свобода руху", en:"Freedom of Movement", lvl:4, school:"ограждення", cls:["Бард","Клірик","Друїд","Слідопит"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С·М" },
    { uk:"Сум'яття", en:"Confusion", lvl:4, school:"зачарування", cls:["Бард","Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"90 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Таємна скриня", en:"Secret Chest", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Усихання", en:"Blight", lvl:4, school:"некромантія", cls:["Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Формування каменю", en:"Stone Shape", lvl:4, school:"перетворення", cls:["Клірик","Друїд","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Хапка лоза", en:"Grasping Vine", lvl:4, school:"прикликання", cls:["Друїд","Слідопит"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Чорні щупальця", en:"Black Tentacles", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"90 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    // --- 5 рівень ---
    { uk:"Єднання", en:"Commune", lvl:5, school:"віщування", cls:["Клірик"], cast:"1 хв", src:"srd", rng:"На себе", dur:"1 хв", comp:"В·С·М", ritual:true },
    { uk:"Єднання з природою", en:"Commune With Nature", lvl:5, school:"віщування", cls:["Друїд","Слідопит"], cast:"1 хв", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С", ritual:true },
    { uk:"Антижиттєва оболонка", en:"Antilife Shell", lvl:5, school:"ограждення", cls:["Друїд"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Виганяючий удар", en:"Banishing Smite", lvl:5, school:"ограждення", cls:["Паладин"], cast:"бонусна дія", src:"phb", conc:true },
    { uk:"Вище відновлення", en:"Greater Restoration", lvl:5, school:"ограждення", cls:["Бард","Клірик","Друїд"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Воскресіння мертвого", en:"Raise Dead", lvl:5, school:"некромантія", cls:["Бард","Клірик","Паладин"], cast:"1 год", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Зараза", en:"Contagion", lvl:5, school:"некромантія", cls:["Клірик","Друїд"], cast:"дія", src:"srd", rng:"Дотик", dur:"7 дн.", comp:"В·С" },
    { uk:"Зміна пам'яті", en:"Modify Memory", lvl:5, school:"зачарування", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Кам'яна стіна", en:"Wall of Stone", lvl:5, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Коло сили", en:"Circle of Power", lvl:5, school:"ограждення", cls:["Паладин"], cast:"дія", src:"phb", conc:true },
    { uk:"Коло телепортації", en:"Teleportation Circle", lvl:5, school:"прикликання", cls:["Бард","Чаклун","Чарівник"], cast:"1 хв", src:"srd", rng:"10 фт", dur:"1 раунд", comp:"В·М" },
    { uk:"Контакт з іншим планом", en:"Contact Other Plane", lvl:5, school:"віщування", cls:["Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"На себе", dur:"1 хв", comp:"В", ritual:true },
    { uk:"Конус холоду", en:"Cone of Cold", lvl:5, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Крок крізь дерева", en:"Tree Stride", lvl:5, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Легенди давнини", en:"Legend Lore", lvl:5, school:"віщування", cls:["Бард","Клірик","Чарівник"], cast:"10 хв", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Личина", en:"Seeming", lvl:5, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"8 год", comp:"В·С" },
    { uk:"Магічна рука", en:"Arcane Hand", lvl:5, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Масове лікування ран", en:"Mass Cure Wounds", lvl:5, school:"прикликання", cls:["Бард","Клірик","Друїд"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Нашестя комах", en:"Insect Plague", lvl:5, school:"прикликання", cls:["Клірик","Друїд","Чаклун"], cast:"дія", src:"srd", rng:"300 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Оживлення предметів", en:"Animate Objects", lvl:5, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Оманливий двійник", en:"Mislead", lvl:5, school:"ілюзії", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"С", conc:true },
    { uk:"Освячення", en:"Hallow", lvl:5, school:"викликання", cls:["Клірик"], cast:"24 год", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Переродження", en:"Reincarnate", lvl:5, school:"перетворення", cls:["Друїд"], cast:"1 год", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Планарні пута", en:"Planar Binding", lvl:5, school:"ограждення", cls:["Бард","Клірик","Друїд","Чарівник"], cast:"1 год", src:"srd", rng:"60 фт", dur:"24 год", comp:"В·С·М" },
    { uk:"Повеління", en:"Geas", lvl:5, school:"зачарування", cls:["Бард","Клірик","Друїд","Паладин","Чарівник"], cast:"1 хв", src:"srd", rng:"60 фт", dur:"30 дн.", comp:"В" },
    { uk:"Полум'яний удар", en:"Flame Strike", lvl:5, school:"викликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Призов дракона", en:"Summon Dragon", lvl:5, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd24", rng:"60 фт", dur:"До 1 год", comp:"В·С·М", conc:true, only24:true },
    { uk:"Призов драконячого духа", en:"Summon Draconic Spirit", lvl:5, school:"прикликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Призов небожителя", en:"Summon Celestial", lvl:5, school:"прикликання", cls:["Клірик","Паладин"], cast:"дія", src:"tce", conc:true },
    { uk:"Прикликання елементаля", en:"Conjure Elemental", lvl:5, school:"прикликання", cls:["Друїд","Чарівник"], cast:"1 хв", src:"srd", rng:"90 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Прикликання зливи", en:"Conjure Volley", lvl:5, school:"прикликання", cls:["Слідопит"], cast:"дія", src:"phb" },
    { uk:"Пробудження", en:"Awaken", lvl:5, school:"перетворення", cls:["Бард","Друїд"], cast:"8 год", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Прохід крізь стіну", en:"Passwall", lvl:5, school:"перетворення", cls:["Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 год", comp:"В·С·М" },
    { uk:"Підкорення особи", en:"Dominate Person", lvl:5, school:"зачарування", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Розсіювання зла і добра", en:"Dispel Evil and Good", lvl:5, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Руйнівна хвиля", en:"Destructive Wave", lvl:5, school:"викликання", cls:["Паладин"], cast:"дія", src:"phb" },
    { uk:"Силова стіна", en:"Wall of Force", lvl:5, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Смертоносна хмара", en:"Cloudkill", lvl:5, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Сновидіння", en:"Dream", lvl:5, school:"ілюзії", cls:["Бард","Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"Особлива", dur:"8 год", comp:"В·С·М" },
    { uk:"Споглядання", en:"Scrying", lvl:5, school:"віщування", cls:["Бард","Клірик","Друїд","Чорнокнижник","Чарівник"], cast:"10 хв", src:"srd", rng:"На себе", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Творення", en:"Creation", lvl:5, school:"ілюзії", cls:["Чаклун","Чарівник"], cast:"1 хв", src:"srd", rng:"30 фт", dur:"Особлива", comp:"В·С·М" },
    { uk:"Телекінез", en:"Telekinesis", lvl:5, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Телепатичний зв'язок", en:"Telepathic Bond", lvl:5, school:"віщування", cls:["Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"1 год", comp:"В·С·М", ritual:true },
    { uk:"Удар сталевого вітру", en:"Steel Wind Strike", lvl:5, school:"прикликання", cls:["Слідопит","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Утримання чудовиська", en:"Hold Monster", lvl:5, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"90 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Швидкий сагайдак", en:"Swift Quiver", lvl:5, school:"перетворення", cls:["Слідопит"], cast:"бонусна дія", src:"phb", conc:true },
    // --- 6 рівень ---
    { uk:"Істинний зір", en:"True Seeing", lvl:6, school:"віщування", cls:["Бард","Клірик","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С·М" },
    { uk:"Бар'єр клинків", en:"Blade Barrier", lvl:6, school:"викликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"90 фт", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Бенкет героїв", en:"Heroes' Feast", lvl:6, school:"прикликання", cls:["Клірик","Друїд"], cast:"10 хв", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Варта й обереги", en:"Guards and Wards", lvl:6, school:"ограждення", cls:["Бард","Чарівник"], cast:"10 хв", src:"srd", rng:"Дотик", dur:"24 год", comp:"В·С·М" },
    { uk:"Вітряна подорож", en:"Wind Walk", lvl:6, school:"перетворення", cls:["Друїд"], cast:"1 хв", src:"srd", rng:"30 фт", dur:"8 год", comp:"В·С·М" },
    { uk:"Заборона", en:"Forbiddance", lvl:6, school:"ограждення", cls:["Клірик"], cast:"10 хв", src:"srd", rng:"Дотик", dur:"24 год", comp:"В·С·М", ritual:true },
    { uk:"Запрограмована ілюзія", en:"Programmed Illusion", lvl:6, school:"ілюзії", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Зцілення", en:"Heal", lvl:6, school:"викликання", cls:["Клірик","Друїд"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Каліцтво", en:"Harm", lvl:6, school:"некромантія", cls:["Клірик"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Коло смерті", en:"Circle of Death", lvl:6, school:"некромантія", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Крижана стіна", en:"Wall of Ice", lvl:6, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Крижана сфера", en:"Freezing Sphere", lvl:6, school:"викликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"300 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Ланцюгова блискавка", en:"Chain Lightning", lvl:6, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Лихий погляд", en:"Eyebite", lvl:6, school:"некромантія", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Масове навіювання", en:"Mass Suggestion", lvl:6, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"24 год", comp:"В·М" },
    { uk:"Миттєвий виклик", en:"Instant Summons", lvl:6, school:"прикликання", cls:["Чарівник"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М", ritual:true },
    { uk:"Нестримний танець", en:"Irresistible Dance", lvl:6, school:"зачарування", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 хв", comp:"В", conc:true },
    { uk:"Обернення на камінь", en:"Flesh to Stone", lvl:6, school:"перетворення", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Передбачливість", en:"Contingency", lvl:6, school:"викликання", cls:["Чарівник"], cast:"10 хв", src:"srd", rng:"На себе", dur:"10 дн.", comp:"В·С·М" },
    { uk:"Перенесення крізь рослини", en:"Transport via Plants", lvl:6, school:"прикликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"10 фт", dur:"1 раунд", comp:"В·С" },
    { uk:"Пересування землі", en:"Move Earth", lvl:6, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 2 год", comp:"В·С·М", conc:true },
    { uk:"Планарний союзник", en:"Planar Ally", lvl:6, school:"прикликання", cls:["Клірик"], cast:"10 хв", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Пошук шляху", en:"Find the Path", lvl:6, school:"віщування", cls:["Бард","Клірик","Друїд"], cast:"1 хв", src:"srd", rng:"На себе", dur:"До 24 год", comp:"В·С·М", conc:true },
    { uk:"Призов ісчадія", en:"Summon Fiend", lvl:6, school:"прикликання", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"tce", conc:true },
    { uk:"Прикликання феї", en:"Conjure Fey", lvl:6, school:"прикликання", cls:["Друїд","Чорнокнижник"], cast:"1 хв", src:"srd", rng:"90 фт", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Розпад", en:"Disintegrate", lvl:6, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Слово повернення", en:"Word of Recall", lvl:6, school:"прикликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"5 фт", dur:"Миттєво", comp:"В" },
    { uk:"Сонячний промінь", en:"Sunbeam", lvl:6, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Створення нежиті", en:"Create Undead", lvl:6, school:"некромантія", cls:["Клірик","Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"10 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Стіна тернів", en:"Wall of Thorns", lvl:6, school:"прикликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 10 хв", comp:"В·С·М", conc:true },
    { uk:"Сфера невразливості", en:"Globe of Invulnerability", lvl:6, school:"ограждення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Чарівний глек", en:"Magic Jar", lvl:6, school:"некромантія", cls:["Чарівник"], cast:"1 хв", src:"srd", rng:"На себе", dur:"Доки не розсіють", comp:"В·С·М" },
    // --- 7 рівень ---
    { uk:"Божественне слово", en:"Divine Word", lvl:7, school:"викликання", cls:["Клірик"], cast:"бонусна дія", src:"srd", rng:"30 фт", dur:"Миттєво", comp:"В" },
    { uk:"Вогняна куля сповільненої дії", en:"Delayed Blast Fireball", lvl:7, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Вогняний шторм", en:"Fire Storm", lvl:7, school:"викликання", cls:["Клірик","Друїд","Чаклун"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Воскресіння", en:"Resurrection", lvl:7, school:"некромантія", cls:["Бард","Клірик"], cast:"1 год", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Ефірність", en:"Etherealness", lvl:7, school:"перетворення", cls:["Бард","Клірик","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"8 год", comp:"В·С" },
    { uk:"Зворотна гравітація", en:"Reverse Gravity", lvl:7, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"100 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Зміна плану", en:"Plane Shift", lvl:7, school:"прикликання", cls:["Клірик","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Магічний меч", en:"Arcane Sword", lvl:7, school:"викликання", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Магічний міраж", en:"Mirage Arcane", lvl:7, school:"ілюзії", cls:["Бард","Друїд","Чарівник"], cast:"10 хв", src:"srd", rng:"У межах зору", dur:"10 дн.", comp:"В·С" },
    { uk:"Перст смерті", en:"Finger of Death", lvl:7, school:"некромантія", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Призматичні бризки", en:"Prismatic Spray", lvl:7, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В·С" },
    { uk:"Прикликання небожителя", en:"Conjure Celestial", lvl:7, school:"прикликання", cls:["Клірик"], cast:"1 хв", src:"srd", rng:"90 фт", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Проєкція образу", en:"Project Image", lvl:7, school:"ілюзії", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"500 миль", dur:"До 24 год", comp:"В·С·М", conc:true },
    { uk:"Регенерація", en:"Regenerate", lvl:7, school:"перетворення", cls:["Бард","Клірик","Друїд"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"1 год", comp:"В·С·М" },
    { uk:"Розкішний особняк", en:"Magnificent Mansion", lvl:7, school:"прикликання", cls:["Бард","Чарівник"], cast:"1 хв", src:"srd", rng:"300 фт", dur:"24 год", comp:"В·С·М" },
    { uk:"Силова клітка", en:"Forcecage", lvl:7, school:"викликання", cls:["Бард","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"100 фт", dur:"1 год", comp:"В·С·М" },
    { uk:"Символ", en:"Symbol", lvl:7, school:"ограждення", cls:["Бард","Клірик","Чарівник"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Симулякр", en:"Simulacrum", lvl:7, school:"ілюзії", cls:["Чарівник"], cast:"12 год", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    { uk:"Телепортація", en:"Teleport", lvl:7, school:"прикликання", cls:["Бард","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"10 фт", dur:"Миттєво", comp:"В" },
    { uk:"Усамітнення", en:"Sequester", lvl:7, school:"перетворення", cls:["Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"Доки не розсіють", comp:"В·С·М" },
    // --- 8 рівень ---
    { uk:"Антимагічне поле", en:"Antimagic Field", lvl:8, school:"ограждення", cls:["Клірик","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Антипатія/Симпатія", en:"Antipathy/Sympathy", lvl:8, school:"зачарування", cls:["Друїд","Чарівник"], cast:"1 год", src:"srd", rng:"60 фт", dur:"10 дн.", comp:"В·С·М" },
    { uk:"Запальна хмара", en:"Incendiary Cloud", lvl:8, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Звірині подоби", en:"Animal Shapes", lvl:8, school:"перетворення", cls:["Друїд"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 24 год", comp:"В·С", conc:true },
    { uk:"Землетрус", en:"Earthquake", lvl:8, school:"викликання", cls:["Клірик","Друїд","Чаклун"], cast:"дія", src:"srd", rng:"500 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Керування погодою", en:"Control Weather", lvl:8, school:"перетворення", cls:["Клірик","Друїд","Чарівник"], cast:"10 хв", src:"srd", rng:"На себе", dur:"До 8 год", comp:"В·С·М", conc:true },
    { uk:"Клон", en:"Clone", lvl:8, school:"некромантія", cls:["Чарівник"], cast:"1 год", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Красномовність", en:"Glibness", lvl:8, school:"перетворення", cls:["Бард","Чорнокнижник"], cast:"дія", src:"srd", rng:"На себе", dur:"1 год", comp:"В" },
    { uk:"Лабіринт", en:"Maze", lvl:8, school:"прикликання", cls:["Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 10 хв", comp:"В·С", conc:true },
    { uk:"Напівплан", en:"Demiplane", lvl:8, school:"прикликання", cls:["Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"1 год", comp:"С" },
    { uk:"Недоумство", en:"Feeblemind", lvl:8, school:"зачарування", cls:["Бард","Друїд","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Підкорення чудовиська", en:"Dominate Monster", lvl:8, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 год", comp:"В·С", conc:true },
    { uk:"Свята аура", en:"Holy Aura", lvl:8, school:"ограждення", cls:["Клірик"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Слово сили: оглушення", en:"Power Word Stun", lvl:8, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Сонячний спалах", en:"Sunburst", lvl:8, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"150 фт", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Цунамі", en:"Tsunami", lvl:8, school:"прикликання", cls:["Друїд"], cast:"1 хв", src:"srd24", rng:"1 миля", dur:"До 6 раунд.", comp:"В·С", conc:true },
    { uk:"Чистий розум", en:"Mind Blank", lvl:8, school:"ограждення", cls:["Бард","Чарівник"], cast:"дія", src:"srd", rng:"Дотик", dur:"24 год", comp:"В·С" },
    // --- 9 рівень ---
    { uk:"Істинне воскресіння", en:"True Resurrection", lvl:9, school:"некромантія", cls:["Клірик","Друїд"], cast:"1 год", src:"srd", rng:"Дотик", dur:"Миттєво", comp:"В·С·М" },
    { uk:"Істинне перевтілення", en:"True Polymorph", lvl:9, school:"перетворення", cls:["Бард","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"30 фт", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Астральна проєкція", en:"Astral Projection", lvl:9, school:"некромантія", cls:["Клірик","Чорнокнижник","Чарівник"], cast:"1 год", src:"srd", rng:"10 фт", dur:"Особлива", comp:"В·С·М" },
    { uk:"Бажання", en:"Wish", lvl:9, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В" },
    { uk:"Брама", en:"Gate", lvl:9, school:"прикликання", cls:["Клірик","Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"До 1 хв", comp:"В·С·М", conc:true },
    { uk:"Буря відплати", en:"Storm of Vengeance", lvl:9, school:"прикликання", cls:["Друїд"], cast:"дія", src:"srd", rng:"У межах зору", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Жахіття", en:"Weird", lvl:9, school:"ілюзії", cls:["Чарівник"], cast:"дія", src:"srd", rng:"120 фт", dur:"До 1 хв", comp:"В·С", conc:true },
    { uk:"Зміна подоби", en:"Shapechange", lvl:9, school:"перетворення", cls:["Друїд","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"До 1 год", comp:"В·С·М", conc:true },
    { uk:"Зупинка часу", en:"Time Stop", lvl:9, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"На себе", dur:"Миттєво", comp:"В" },
    { uk:"Масове зцілення", en:"Mass Heal", lvl:9, school:"прикликання", cls:["Клірик"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В·С" },
    { uk:"Метеоритний дощ", en:"Meteor Swarm", lvl:9, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", src:"srd", rng:"1 миля", dur:"Миттєво", comp:"В·С" },
    { uk:"Передбачення", en:"Foresight", lvl:9, school:"віщування", cls:["Бард","Друїд","Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"Дотик", dur:"8 год", comp:"В·С·М" },
    { uk:"Призматична стіна", en:"Prismatic Wall", lvl:9, school:"ограждення", cls:["Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"10 хв", comp:"В·С" },
    { uk:"Психічний крик", en:"Psychic Scream", lvl:9, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"xge" },
    { uk:"Слово сили: зцілення", en:"Power Word Heal", lvl:9, school:"зачарування", cls:["Бард","Клірик"], cast:"дія", src:"srd24", rng:"60 фт", dur:"Миттєво" },
    { uk:"Слово сили: смерть", en:"Power Word Kill", lvl:9, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", src:"srd", rng:"60 фт", dur:"Миттєво", comp:"В" },
    { uk:"Ув'язнення", en:"Imprisonment", lvl:9, school:"ограждення", cls:["Чорнокнижник","Чарівник"], cast:"1 хв", src:"srd", rng:"30 фт", dur:"Доки не розсіють", comp:"В·С·М" },
  ];

  // Назва → закляття, для швидкого пошуку за українською назвою
  window.SPELL_BY_NAME = {};
  window.SPELLS.forEach(function (s) { window.SPELL_BY_NAME[s.uk] = s; });

  /* Чи проходить закляття крізь фільтр джерел (f — об'єкт на кшталт
     SPELL_FILTER; якщо не передали, беремо поточний). */
  window.spellAllowed = function (s, f) {
    f = f || window.SPELL_FILTER;
    if (s.only24 && !f.ed2024) return false;
    return f[s.src] !== false;
  };

  /* Розмітка опису: ділимо текст на шматки й позначаємо ті, що варто виділити —
     кубики шкоди, порятунки, DC, дистанції, стани, дія/бонусна дія. Один розбір
     на двох: екран малює їх жирним у HTML, PDF — жирним накресленням шрифту. */
  var RICH = new RegExp([
    "\\d+d\\d+(?:\\s*[+\u2212-]\\s*\\d+)?",
    "DC\\s*\\d+",
    "(?:Strength|Dexterity|Constitution|Intelligence|Wisdom|Charisma)\\s+saving\\s+throw",
    "\\d+(?:[- ])(?:miles|mile|feet|foot)(?:-(?:radius|long|wide|tall|high|diameter|square|cube|cone|line))?",
    "(?:acid|bludgeoning|cold|fire|force|lightning|necrotic|piercing|poison|psychic|radiant|slashing|thunder)\\s+damage",
    "\\b(?:advantage|disadvantage)\\b",
    "\\b(?:blinded|charmed|deafened|frightened|grappled|incapacitated|invisible|paralyzed|petrified|poisoned|prone|restrained|stunned|unconscious)\\b",
    "\\b(?:bonus action|reaction|concentration)\\b",
    "\\b(?:temporary hit points|hit points)\\b"
  ].join("|"), "gi");
  window.spellRich = function (text) {
    var s = String(text == null ? "" : text), out = [], last = 0, m;
    RICH.lastIndex = 0;
    while ((m = RICH.exec(s)) !== null) {
      if (m.index > last) out.push({ s: s.slice(last, m.index), b: false });
      out.push({ s: m[0], b: true });
      last = m.index + m[0].length;
      if (RICH.lastIndex === m.index) RICH.lastIndex++;    // страховка від порожнього збігу
    }
    if (last < s.length) out.push({ s: s.slice(last), b: false });
    return out;
  };

  /* Закляття класу певного рівня (lvl === null — усі рівні), уже відфільтровані
     за джерелами. Таємний трюкач і Лицар-маг питають список Чарівника. */
  window.spellsFor = function (cls, lvl, f) {
    return window.SPELLS.filter(function (s) {
      return s.cls.indexOf(cls) >= 0 && (lvl == null || s.lvl === lvl) && window.spellAllowed(s, f);
    });
  };
})();
