/* =========================================================================
   ЗАКЛЯТТЯ — шар даних (SRD 5.1), 319 шт.

   Поки що це лише довідник: назва, рівень, школа, класи, час чаклування,
   ритуал і концентрація. Описів тут немає навмисне — вони роздули б файл
   учетверо (чотири мови), а для вибору заклять і запису в чарник досить назв.

   Поля: uk — українська назва (канон, нею працює решта коду), en — оригінал
   для звірки, lvl 0 = замовляння, cls — класи зі списком цього закляття
   (Таємний трюкач і Лицар-маг беруть зі списку Чарівника).

   Джерело: System Reference Document 5.1 © Wizards of the Coast LLC,
   ліцензія Creative Commons Attribution 4.0 International (CC-BY-4.0).
   Українські назви — наш переклад; звірка й правки — у SPELLS.md.
   ========================================================================= */
(function () {
  "use strict";

  // Школи магії: ключ — англійська, значення — як пишемо в тексті («зі школи …»)
  window.SPELL_SCHOOLS = {
      "ограждення": "Abjuration",
      "прикликання": "Conjuration",
      "віщування": "Divination",
      "зачарування": "Enchantment",
      "викликання": "Evocation",
      "ілюзії": "Illusion",
      "некромантія": "Necromancy",
      "перетворення": "Transmutation"
  };

  window.SPELLS = [
    // --- замовляння (0 рівень) ---
    { uk:"Бризки кислоти", en:"Acid Splash", lvl:0, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Бризки отрути", en:"Poison Spray", lvl:0, school:"прикликання", cls:["Чаклун","Чорнокнижник","Чарівник","Друїд"], cast:"дія" },
    { uk:"Вогняна стріла", en:"Fire Bolt", lvl:0, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Друїдство", en:"Druidcraft", lvl:0, school:"перетворення", cls:["Друїд"], cast:"дія" },
    { uk:"Дубець", en:"Shillelagh", lvl:0, school:"перетворення", cls:["Друїд"], cast:"бонусна дія" },
    { uk:"Електричний дотик", en:"Shocking Grasp", lvl:0, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Злісні насмішки", en:"Vicious Mockery", lvl:0, school:"зачарування", cls:["Бард"], cast:"дія" },
    { uk:"Лагодження", en:"Mending", lvl:0, school:"перетворення", cls:["Клірик","Бард","Друїд","Чаклун","Чарівник"], cast:"1 хв" },
    { uk:"Мала ілюзія", en:"Minor Illusion", lvl:0, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Містичний вибух", en:"Eldritch Blast", lvl:0, school:"викликання", cls:["Чорнокнижник"], cast:"дія" },
    { uk:"Настанова", en:"Guidance", lvl:0, school:"віщування", cls:["Клірик","Друїд"], cast:"дія", conc:true },
    { uk:"Опір", en:"Resistance", lvl:0, school:"ограждення", cls:["Клірик","Друїд"], cast:"дія", conc:true },
    { uk:"Порятунок помираючого", en:"Spare the Dying", lvl:0, school:"некромантія", cls:["Клірик"], cast:"дія" },
    { uk:"Послання", en:"Message", lvl:0, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Промінь холоду", en:"Ray of Frost", lvl:0, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Рука мага", en:"Mage Hand", lvl:0, school:"прикликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Священне полум'я", en:"Sacred Flame", lvl:0, school:"викликання", cls:["Клірик"], cast:"дія" },
    { uk:"Світло", en:"Light", lvl:0, school:"викликання", cls:["Бард","Клірик","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Створення полум'я", en:"Produce Flame", lvl:0, school:"прикликання", cls:["Друїд"], cast:"дія" },
    { uk:"Тавматургія", en:"Thaumaturgy", lvl:0, school:"перетворення", cls:["Клірик"], cast:"дія" },
    { uk:"Танцюючі вогники", en:"Dancing Lights", lvl:0, school:"викликання", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Точний удар", en:"True Strike", lvl:0, school:"віщування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Фокуси", en:"Prestidigitation", lvl:0, school:"перетворення", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Холодний дотик", en:"Chill Touch", lvl:0, school:"некромантія", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    // --- 1 рівень ---
    { uk:"Ілюзорний напис", en:"Illusory Script", lvl:1, school:"ілюзії", cls:["Бард","Чорнокнижник","Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Барвисті бризки", en:"Color Spray", lvl:1, school:"ілюзії", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Безмовний образ", en:"Silent Image", lvl:1, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Благословення", en:"Bless", lvl:1, school:"зачарування", cls:["Клірик","Паладин"], cast:"дія", conc:true },
    { uk:"Божественна прихильність", en:"Divine Favor", lvl:1, school:"викликання", cls:["Паладин"], cast:"бонусна дія", conc:true },
    { uk:"Броня мага", en:"Mage Armor", lvl:1, school:"ограждення", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Виявлення зла і добра", en:"Detect Evil and Good", lvl:1, school:"віщування", cls:["Клірик","Паладин"], cast:"дія", conc:true },
    { uk:"Виявлення магії", en:"Detect Magic", lvl:1, school:"віщування", cls:["Бард","Клірик","Друїд","Паладин","Слідопит","Чаклун","Чарівник"], cast:"дія", ritual:true, conc:true },
    { uk:"Виявлення отрути і хвороби", en:"Detect Poison and Disease", lvl:1, school:"віщування", cls:["Клірик","Друїд","Паладин","Слідопит"], cast:"дія", ritual:true, conc:true },
    { uk:"Героїзм", en:"Heroism", lvl:1, school:"зачарування", cls:["Бард","Паладин"], cast:"дія", conc:true },
    { uk:"Громова хвиля", en:"Thunderwave", lvl:1, school:"викликання", cls:["Бард","Друїд","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Довгий крок", en:"Longstrider", lvl:1, school:"перетворення", cls:["Бард","Друїд","Слідопит","Чарівник"], cast:"дія" },
    { uk:"Дружба з тваринами", en:"Animal Friendship", lvl:1, school:"зачарування", cls:["Бард","Друїд","Слідопит"], cast:"дія" },
    { uk:"Захист від зла і добра", en:"Protection from Evil and Good", lvl:1, school:"ограждення", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Зачарування особи", en:"Charm Person", lvl:1, school:"зачарування", cls:["Бард","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Згуба", en:"Bane", lvl:1, school:"зачарування", cls:["Бард","Клірик"], cast:"дія", conc:true },
    { uk:"Летючий диск", en:"Floating Disk", lvl:1, school:"прикликання", cls:["Чарівник"], cast:"дія", ritual:true },
    { uk:"Лікування ран", en:"Cure Wounds", lvl:1, school:"викликання", cls:["Бард","Клірик","Друїд","Паладин","Слідопит"], cast:"дія" },
    { uk:"Магічна стріла", en:"Magic Missile", lvl:1, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Маскування", en:"Disguise Self", lvl:1, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Мастило", en:"Grease", lvl:1, school:"прикликання", cls:["Чарівник"], cast:"дія" },
    { uk:"Мітка мисливця", en:"Hunter's Mark", lvl:1, school:"віщування", cls:["Слідопит"], cast:"бонусна дія", conc:true },
    { uk:"Наказ", en:"Command", lvl:1, school:"зачарування", cls:["Клірик","Паладин"], cast:"дія" },
    { uk:"Нанесення ран", en:"Inflict Wounds", lvl:1, school:"некромантія", cls:["Клірик"], cast:"дія" },
    { uk:"Невидимий слуга", en:"Unseen Servant", lvl:1, school:"прикликання", cls:["Бард","Чорнокнижник","Чарівник"], cast:"дія", ritual:true },
    { uk:"Несправжнє життя", en:"False Life", lvl:1, school:"некромантія", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Нестримний регіт", en:"Hideous Laughter", lvl:1, school:"зачарування", cls:["Бард","Чарівник"], cast:"дія", conc:true },
    { uk:"Обплутування", en:"Entangle", lvl:1, school:"прикликання", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Очищення їжі та питва", en:"Purify Food and Drink", lvl:1, school:"перетворення", cls:["Клірик","Друїд","Паладин"], cast:"дія", ritual:true },
    { uk:"Падіння пір'їнкою", en:"Feather Fall", lvl:1, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"реакція" },
    { uk:"Палаючі руки", en:"Burning Hands", lvl:1, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Пекельна відплата", en:"Hellish Rebuke", lvl:1, school:"викликання", cls:["Чорнокнижник"], cast:"реакція" },
    { uk:"Пошук фамільяра", en:"Find Familiar", lvl:1, school:"прикликання", cls:["Чарівник"], cast:"1 год", ritual:true },
    { uk:"Розмова з тваринами", en:"Speak with Animals", lvl:1, school:"віщування", cls:["Бард","Друїд","Слідопит"], cast:"дія", ritual:true },
    { uk:"Розпізнавання", en:"Identify", lvl:1, school:"віщування", cls:["Бард","Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Розуміння мов", en:"Comprehend Languages", lvl:1, school:"віщування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", ritual:true },
    { uk:"Святилище", en:"Sanctuary", lvl:1, school:"ограждення", cls:["Клірик"], cast:"бонусна дія" },
    { uk:"Скерований промінь", en:"Guiding Bolt", lvl:1, school:"викликання", cls:["Клірик"], cast:"дія" },
    { uk:"Сон", en:"Sleep", lvl:1, school:"зачарування", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Створення або знищення води", en:"Create or Destroy Water", lvl:1, school:"перетворення", cls:["Клірик","Друїд"], cast:"дія" },
    { uk:"Стрибок", en:"Jump", lvl:1, school:"перетворення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Тривога", en:"Alarm", lvl:1, school:"ограждення", cls:["Слідопит","Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Хмара туману", en:"Fog Cloud", lvl:1, school:"прикликання", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Цілюща ягода", en:"Goodberry", lvl:1, school:"перетворення", cls:["Друїд","Слідопит"], cast:"дія" },
    { uk:"Цілюще слово", en:"Healing Word", lvl:1, school:"викликання", cls:["Бард","Клірик","Друїд"], cast:"бонусна дія" },
    { uk:"Чарівний вогонь", en:"Faerie Fire", lvl:1, school:"викликання", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Швидкий відступ", en:"Expeditious Retreat", lvl:1, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"бонусна дія", conc:true },
    { uk:"Щит", en:"Shield", lvl:1, school:"ограждення", cls:["Чаклун","Чарівник"], cast:"реакція" },
    { uk:"Щит віри", en:"Shield of Faith", lvl:1, school:"ограждення", cls:["Клірик","Паладин"], cast:"бонусна дія", conc:true },
    // --- 2 рівень ---
    { uk:"Бачення невидимого", en:"See Invisibility", lvl:2, school:"віщування", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Безслідний шлях", en:"Pass Without Trace", lvl:2, school:"ограждення", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    { uk:"Виявлення думок", en:"Detect Thoughts", lvl:2, school:"віщування", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Вогняна сфера", en:"Flaming Sphere", lvl:2, school:"прикликання", cls:["Друїд","Чарівник"], cast:"дія", conc:true },
    { uk:"Вогняний клинок", en:"Flame Blade", lvl:2, school:"викликання", cls:["Друїд"], cast:"бонусна дія", conc:true },
    { uk:"Ворожіння", en:"Augury", lvl:2, school:"віщування", cls:["Клірик"], cast:"1 хв", ritual:true },
    { uk:"Відмикання", en:"Knock", lvl:2, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Вічне полум'я", en:"Continual Flame", lvl:2, school:"викликання", cls:["Клірик","Чарівник"], cast:"дія" },
    { uk:"Дзеркальний образ", en:"Mirror Image", lvl:2, school:"ілюзії", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Допомога", en:"Aid", lvl:2, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія" },
    { uk:"Дроблення", en:"Shatter", lvl:2, school:"викликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Духовна зброя", en:"Spiritual Weapon", lvl:2, school:"викликання", cls:["Клірик"], cast:"бонусна дія" },
    { uk:"Заворожування", en:"Enthrall", lvl:2, school:"зачарування", cls:["Бард","Чорнокнижник"], cast:"дія" },
    { uk:"Заспокоєння емоцій", en:"Calm Emotions", lvl:2, school:"зачарування", cls:["Бард","Клірик"], cast:"дія", conc:true },
    { uk:"Захисні узи", en:"Warding Bond", lvl:2, school:"ограждення", cls:["Клірик"], cast:"дія" },
    { uk:"Захист від отрути", en:"Protection from Poison", lvl:2, school:"ограждення", cls:["Клірик","Друїд","Паладин","Слідопит"], cast:"дія" },
    { uk:"Збільшення/Зменшення", en:"Enlarge/Reduce", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Зміна себе", en:"Alter Self", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Зона правди", en:"Zone of Truth", lvl:2, school:"зачарування", cls:["Бард","Клірик","Паладин"], cast:"дія" },
    { uk:"Кислотна стріла", en:"Acid Arrow", lvl:2, school:"викликання", cls:["Чарівник"], cast:"дія" },
    { uk:"Кора", en:"Barkskin", lvl:2, school:"перетворення", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    { uk:"Левітація", en:"Levitate", lvl:2, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Магічна аура арканіста", en:"Arcanist's Magic Aura", lvl:2, school:"ілюзії", cls:["Чарівник"], cast:"дія" },
    { uk:"Магічна зброя", en:"Magic Weapon", lvl:2, school:"перетворення", cls:["Паладин","Чарівник"], cast:"бонусна дія", conc:true },
    { uk:"Магічний замок", en:"Arcane Lock", lvl:2, school:"ограждення", cls:["Чарівник"], cast:"дія" },
    { uk:"Мале відновлення", en:"Lesser Restoration", lvl:2, school:"ограждення", cls:["Бард","Клірик","Друїд","Паладин","Слідопит"], cast:"дія" },
    { uk:"Молитва зцілення", en:"Prayer of Healing", lvl:2, school:"викликання", cls:["Клірик"], cast:"10 хв" },
    { uk:"Місячний промінь", en:"Moonbeam", lvl:2, school:"викликання", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Навіювання", en:"Suggestion", lvl:2, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Невидимість", en:"Invisibility", lvl:2, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Павутина", en:"Web", lvl:2, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Павуче лазіння", en:"Spider Climb", lvl:2, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Палючий промінь", en:"Scorching Ray", lvl:2, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Порив вітру", en:"Gust of Wind", lvl:2, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Посилення характеристики", en:"Enhance Ability", lvl:2, school:"перетворення", cls:["Бард","Клірик","Друїд","Чаклун"], cast:"дія", conc:true },
    { uk:"Пошук пасток", en:"Find Traps", lvl:2, school:"віщування", cls:["Клірик","Друїд","Слідопит"], cast:"дія" },
    { uk:"Пошук предмета", en:"Locate Object", lvl:2, school:"віщування", cls:["Бард","Клірик","Друїд","Паладин","Слідопит","Чарівник"], cast:"дія", conc:true },
    { uk:"Пошук скакуна", en:"Find Steed", lvl:2, school:"прикликання", cls:["Паладин"], cast:"10 хв" },
    { uk:"Пошук тварин або рослин", en:"Locate Animals or Plants", lvl:2, school:"віщування", cls:["Бард","Друїд","Слідопит"], cast:"дія", ritual:true },
    { uk:"Промінь знесилення", en:"Ray of Enfeeblement", lvl:2, school:"некромантія", cls:["Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Розжарення металу", en:"Heat Metal", lvl:2, school:"перетворення", cls:["Бард","Друїд"], cast:"дія", conc:true },
    { uk:"Розмитість", en:"Blur", lvl:2, school:"ілюзії", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Сліпота/Глухота", en:"Blindness/Deafness", lvl:2, school:"некромантія", cls:["Бард","Клірик","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Спокійний спочинок", en:"Gentle Repose", lvl:2, school:"некромантія", cls:["Клірик","Чарівник"], cast:"дія", ritual:true },
    { uk:"Тавруючий удар", en:"Branding Smite", lvl:2, school:"викликання", cls:["Паладин"], cast:"бонусна дія", conc:true },
    { uk:"Тварина-посланець", en:"Animal Messenger", lvl:2, school:"зачарування", cls:["Бард","Друїд","Слідопит"], cast:"дія", ritual:true },
    { uk:"Темнобачення", en:"Darkvision", lvl:2, school:"перетворення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Темрява", en:"Darkness", lvl:2, school:"викликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Тиша", en:"Silence", lvl:2, school:"ілюзії", cls:["Бард","Клірик","Слідопит"], cast:"дія", ritual:true, conc:true },
    { uk:"Трюк з мотузкою", en:"Rope Trick", lvl:2, school:"перетворення", cls:["Чарівник"], cast:"дія" },
    { uk:"Туманний крок", en:"Misty Step", lvl:2, school:"прикликання", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"бонусна дія" },
    { uk:"Утримання особи", en:"Hold Person", lvl:2, school:"зачарування", cls:["Бард","Клірик","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Чарівні вуста", en:"Magic Mouth", lvl:2, school:"ілюзії", cls:["Бард","Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Шипи", en:"Spike Growth", lvl:2, school:"перетворення", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    // --- 3 рівень ---
    { uk:"Блискавка", en:"Lightning Bolt", lvl:3, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Вампірський дотик", en:"Vampiric Touch", lvl:3, school:"некромантія", cls:["Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Великий образ", en:"Major Image", lvl:3, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Виклик блискавки", en:"Call Lightning", lvl:3, school:"прикликання", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Вогняна куля", en:"Fireball", lvl:3, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Водне дихання", en:"Water Breathing", lvl:3, school:"перетворення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", ritual:true },
    { uk:"Вістка", en:"Sending", lvl:3, school:"викликання", cls:["Бард","Клірик","Чарівник"], cast:"дія" },
    { uk:"Газоподібна форма", en:"Gaseous Form", lvl:3, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Гіпнотичний візерунок", en:"Hypnotic Pattern", lvl:3, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Денне світло", en:"Daylight", lvl:3, school:"викликання", cls:["Клірик","Друїд","Паладин","Слідопит","Чаклун"], cast:"дія" },
    { uk:"Духи-охоронці", en:"Spirit Guardians", lvl:3, school:"прикликання", cls:["Клірик"], cast:"дія", conc:true },
    { uk:"Захист від стихій", en:"Protection From Energy", lvl:3, school:"ограждення", cls:["Клірик","Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Злиття з каменем", en:"Meld Into Stone", lvl:3, school:"перетворення", cls:["Клірик"], cast:"дія", ritual:true },
    { uk:"Зняття прокляття", en:"Remove Curse", lvl:3, school:"ограждення", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Контрзакляття", en:"Counterspell", lvl:3, school:"ограждення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"реакція" },
    { uk:"Крижана буря", en:"Sleet Storm", lvl:3, school:"прикликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Магічне коло", en:"Magic Circle", lvl:3, school:"ограждення", cls:["Клірик","Паладин","Чорнокнижник","Чарівник"], cast:"1 хв" },
    { uk:"Маленька хатина", en:"Tiny Hut", lvl:3, school:"викликання", cls:["Бард","Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Масове цілюще слово", en:"Mass Healing Word", lvl:3, school:"викликання", cls:["Клірик"], cast:"бонусна дія" },
    { uk:"Маяк надії", en:"Beacon of Hope", lvl:3, school:"ограждення", cls:["Клірик"], cast:"дія", conc:true },
    { uk:"Мерехтіння", en:"Blink", lvl:3, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Мови", en:"Tongues", lvl:3, school:"віщування", cls:["Бард","Клірик","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Накладення прокляття", en:"Bestow Curse", lvl:3, school:"некромантія", cls:["Бард","Клірик","Чарівник"], cast:"дія", conc:true },
    { uk:"Невиявність", en:"Nondetection", lvl:3, school:"ограждення", cls:["Бард","Слідопит","Чарівник"], cast:"дія" },
    { uk:"Оживлення мертвих", en:"Animate Dead", lvl:3, school:"некромантія", cls:["Клірик","Чарівник"], cast:"1 хв" },
    { uk:"Охоронний гліф", en:"Glyph of Warding", lvl:3, school:"ограждення", cls:["Бард","Клірик","Чарівник"], cast:"1 год" },
    { uk:"Повернення до життя", en:"Revivify", lvl:3, school:"прикликання", cls:["Клірик","Паладин"], cast:"дія" },
    { uk:"Політ", en:"Fly", lvl:3, school:"перетворення", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Прикликання тварин", en:"Conjure Animals", lvl:3, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    { uk:"Примарний скакун", en:"Phantom Steed", lvl:3, school:"ілюзії", cls:["Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Пришвидшення", en:"Haste", lvl:3, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Розмова з мертвими", en:"Speak with Dead", lvl:3, school:"некромантія", cls:["Бард","Клірик"], cast:"дія" },
    { uk:"Розмова з рослинами", en:"Speak with Plants", lvl:3, school:"перетворення", cls:["Бард","Друїд","Слідопит"], cast:"дія" },
    { uk:"Розсіювання магії", en:"Dispel Magic", lvl:3, school:"ограждення", cls:["Бард","Клірик","Друїд","Паладин","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Ріст рослин", en:"Plant Growth", lvl:3, school:"перетворення", cls:["Бард","Друїд","Слідопит"], cast:"дія" },
    { uk:"Смердюча хмара", en:"Stinking Cloud", lvl:3, school:"прикликання", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Сповільнення", en:"Slow", lvl:3, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Створення їжі та води", en:"Create Food and Water", lvl:3, school:"прикликання", cls:["Клірик","Друїд","Паладин"], cast:"дія" },
    { uk:"Страх", en:"Fear", lvl:3, school:"ілюзії", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Стіна вітру", en:"Wind Wall", lvl:3, school:"викликання", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    { uk:"Ходіння по воді", en:"Water Walk", lvl:3, school:"перетворення", cls:["Клірик","Друїд","Слідопит","Чаклун"], cast:"дія", ritual:true },
    { uk:"Ясновидіння", en:"Clairvoyance", lvl:3, school:"віщування", cls:["Бард","Клірик","Чаклун","Чарівник"], cast:"10 хв", conc:true },
    // --- 4 рівень ---
    { uk:"Ілюзорна місцевість", en:"Hallucinatory Terrain", lvl:4, school:"ілюзії", cls:["Бард","Друїд","Чорнокнижник","Чарівник"], cast:"10 хв" },
    { uk:"Вартовий віри", en:"Guardian of Faith", lvl:4, school:"прикликання", cls:["Клірик"], cast:"дія" },
    { uk:"Вигнання", en:"Banishment", lvl:4, school:"ограждення", cls:["Клірик","Паладин","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Виготовлення", en:"Fabricate", lvl:4, school:"перетворення", cls:["Чарівник"], cast:"10 хв" },
    { uk:"Вища невидимість", en:"Greater Invisibility", lvl:4, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Вогняна стіна", en:"Wall of Fire", lvl:4, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Вогняний щит", en:"Fire Shield", lvl:4, school:"викликання", cls:["Чарівник"], cast:"дія" },
    { uk:"Вірний пес", en:"Faithful Hound", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія" },
    { uk:"Гігантська комаха", en:"Giant Insect", lvl:4, school:"перетворення", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Кам'яна шкіра", en:"Stoneskin", lvl:4, school:"ограждення", cls:["Друїд","Слідопит","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Керування водою", en:"Control Water", lvl:4, school:"перетворення", cls:["Клірик","Друїд","Чарівник"], cast:"дія", conc:true },
    { uk:"Крижаний шторм", en:"Ice Storm", lvl:4, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Магічне око", en:"Arcane Eye", lvl:4, school:"віщування", cls:["Клірик","Чарівник"], cast:"дія", conc:true },
    { uk:"Непробивна сфера", en:"Resilient Sphere", lvl:4, school:"викликання", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Оберіг від смерті", en:"Death Ward", lvl:4, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія" },
    { uk:"Перевтілення", en:"Polymorph", lvl:4, school:"перетворення", cls:["Бард","Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Пошук істоти", en:"Locate Creature", lvl:4, school:"віщування", cls:["Бард","Клірик","Друїд","Паладин","Слідопит","Чарівник"], cast:"дія", conc:true },
    { uk:"Приватне святилище", en:"Private Sanctum", lvl:4, school:"ограждення", cls:["Чарівник"], cast:"10 хв" },
    { uk:"Прикликання лісових створінь", en:"Conjure Woodland Beings", lvl:4, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    { uk:"Прикликання малих елементалів", en:"Conjure Minor Elementals", lvl:4, school:"прикликання", cls:["Друїд","Чарівник"], cast:"1 хв", conc:true },
    { uk:"Примарний убивця", en:"Phantasmal Killer", lvl:4, school:"ілюзії", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Примус", en:"Compulsion", lvl:4, school:"зачарування", cls:["Бард"], cast:"дія", conc:true },
    { uk:"Провидіння", en:"Divination", lvl:4, school:"віщування", cls:["Друїд"], cast:"дія", ritual:true },
    { uk:"Просторові двері", en:"Dimension Door", lvl:4, school:"прикликання", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Підкорення звіра", en:"Dominate Beast", lvl:4, school:"зачарування", cls:["Друїд","Чаклун"], cast:"дія", conc:true },
    { uk:"Свобода руху", en:"Freedom of Movement", lvl:4, school:"ограждення", cls:["Бард","Клірик","Друїд","Слідопит"], cast:"дія" },
    { uk:"Сум'яття", en:"Confusion", lvl:4, school:"зачарування", cls:["Бард","Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Таємна скриня", en:"Secret Chest", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія" },
    { uk:"Усихання", en:"Blight", lvl:4, school:"некромантія", cls:["Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Формування каменю", en:"Stone Shape", lvl:4, school:"перетворення", cls:["Клірик","Друїд","Чарівник"], cast:"дія" },
    { uk:"Чорні щупальця", en:"Black Tentacles", lvl:4, school:"прикликання", cls:["Чарівник"], cast:"дія", conc:true },
    // --- 5 рівень ---
    { uk:"Єднання", en:"Commune", lvl:5, school:"віщування", cls:["Клірик"], cast:"1 хв", ritual:true },
    { uk:"Єднання з природою", en:"Commune With Nature", lvl:5, school:"віщування", cls:["Друїд","Слідопит"], cast:"1 хв", ritual:true },
    { uk:"Антижиттєва оболонка", en:"Antilife Shell", lvl:5, school:"ограждення", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Вище відновлення", en:"Greater Restoration", lvl:5, school:"ограждення", cls:["Бард","Клірик","Друїд"], cast:"дія" },
    { uk:"Воскресіння мертвого", en:"Raise Dead", lvl:5, school:"некромантія", cls:["Бард","Клірик","Паладин"], cast:"1 год" },
    { uk:"Зараза", en:"Contagion", lvl:5, school:"некромантія", cls:["Клірик","Друїд"], cast:"дія" },
    { uk:"Зміна пам'яті", en:"Modify Memory", lvl:5, school:"зачарування", cls:["Бард","Чарівник"], cast:"дія", conc:true },
    { uk:"Кам'яна стіна", en:"Wall of Stone", lvl:5, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Коло телепортації", en:"Teleportation Circle", lvl:5, school:"прикликання", cls:["Бард","Чаклун","Чарівник"], cast:"1 хв" },
    { uk:"Контакт з іншим планом", en:"Contact Other Plane", lvl:5, school:"віщування", cls:["Чорнокнижник","Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Конус холоду", en:"Cone of Cold", lvl:5, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Крок крізь дерева", en:"Tree Stride", lvl:5, school:"прикликання", cls:["Друїд","Слідопит"], cast:"дія", conc:true },
    { uk:"Легенди давнини", en:"Legend Lore", lvl:5, school:"віщування", cls:["Бард","Клірик","Чарівник"], cast:"10 хв" },
    { uk:"Личина", en:"Seeming", lvl:5, school:"ілюзії", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Магічна рука", en:"Arcane Hand", lvl:5, school:"викликання", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Масове лікування ран", en:"Mass Cure Wounds", lvl:5, school:"прикликання", cls:["Бард","Клірик","Друїд"], cast:"дія" },
    { uk:"Нашестя комах", en:"Insect Plague", lvl:5, school:"прикликання", cls:["Клірик","Друїд","Чаклун"], cast:"дія", conc:true },
    { uk:"Оживлення предметів", en:"Animate Objects", lvl:5, school:"перетворення", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Оманливий двійник", en:"Mislead", lvl:5, school:"ілюзії", cls:["Бард","Чарівник"], cast:"дія", conc:true },
    { uk:"Освячення", en:"Hallow", lvl:5, school:"викликання", cls:["Клірик"], cast:"24 год" },
    { uk:"Переродження", en:"Reincarnate", lvl:5, school:"перетворення", cls:["Друїд"], cast:"1 год" },
    { uk:"Планарні пута", en:"Planar Binding", lvl:5, school:"ограждення", cls:["Бард","Клірик","Друїд","Чарівник"], cast:"1 год" },
    { uk:"Повеління", en:"Geas", lvl:5, school:"зачарування", cls:["Бард","Клірик","Друїд","Паладин","Чарівник"], cast:"1 хв" },
    { uk:"Полум'яний удар", en:"Flame Strike", lvl:5, school:"викликання", cls:["Клірик"], cast:"дія" },
    { uk:"Прикликання елементаля", en:"Conjure Elemental", lvl:5, school:"прикликання", cls:["Друїд","Чарівник"], cast:"1 хв", conc:true },
    { uk:"Пробудження", en:"Awaken", lvl:5, school:"перетворення", cls:["Бард","Друїд"], cast:"8 год" },
    { uk:"Прохід крізь стіну", en:"Passwall", lvl:5, school:"перетворення", cls:["Чарівник"], cast:"дія" },
    { uk:"Підкорення особи", en:"Dominate Person", lvl:5, school:"зачарування", cls:["Бард","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Розсіювання зла і добра", en:"Dispel Evil and Good", lvl:5, school:"ограждення", cls:["Клірик","Паладин"], cast:"дія", conc:true },
    { uk:"Силова стіна", en:"Wall of Force", lvl:5, school:"викликання", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Смертоносна хмара", en:"Cloudkill", lvl:5, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Сновидіння", en:"Dream", lvl:5, school:"ілюзії", cls:["Бард","Чорнокнижник","Чарівник"], cast:"1 хв" },
    { uk:"Споглядання", en:"Scrying", lvl:5, school:"віщування", cls:["Бард","Клірик","Друїд","Чорнокнижник","Чарівник"], cast:"10 хв", conc:true },
    { uk:"Творення", en:"Creation", lvl:5, school:"ілюзії", cls:["Чаклун","Чарівник"], cast:"1 хв" },
    { uk:"Телекінез", en:"Telekinesis", lvl:5, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Телепатичний зв'язок", en:"Telepathic Bond", lvl:5, school:"віщування", cls:["Чарівник"], cast:"дія", ritual:true },
    { uk:"Утримання чудовиська", en:"Hold Monster", lvl:5, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    // --- 6 рівень ---
    { uk:"Істинний зір", en:"True Seeing", lvl:6, school:"віщування", cls:["Бард","Клірик","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Бар'єр клинків", en:"Blade Barrier", lvl:6, school:"викликання", cls:["Клірик"], cast:"дія", conc:true },
    { uk:"Бенкет героїв", en:"Heroes' Feast", lvl:6, school:"прикликання", cls:["Клірик","Друїд"], cast:"10 хв" },
    { uk:"Варта й обереги", en:"Guards and Wards", lvl:6, school:"ограждення", cls:["Бард","Чарівник"], cast:"10 хв" },
    { uk:"Вітряна подорож", en:"Wind Walk", lvl:6, school:"перетворення", cls:["Друїд"], cast:"1 хв" },
    { uk:"Заборона", en:"Forbiddance", lvl:6, school:"ограждення", cls:["Клірик"], cast:"10 хв", ritual:true },
    { uk:"Запрограмована ілюзія", en:"Programmed Illusion", lvl:6, school:"ілюзії", cls:["Бард","Чарівник"], cast:"дія" },
    { uk:"Зцілення", en:"Heal", lvl:6, school:"викликання", cls:["Клірик","Друїд"], cast:"дія" },
    { uk:"Каліцтво", en:"Harm", lvl:6, school:"некромантія", cls:["Клірик"], cast:"дія" },
    { uk:"Коло смерті", en:"Circle of Death", lvl:6, school:"некромантія", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Крижана стіна", en:"Wall of Ice", lvl:6, school:"викликання", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Крижана сфера", en:"Freezing Sphere", lvl:6, school:"викликання", cls:["Чарівник"], cast:"дія" },
    { uk:"Ланцюгова блискавка", en:"Chain Lightning", lvl:6, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Лихий погляд", en:"Eyebite", lvl:6, school:"некромантія", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Масове навіювання", en:"Mass Suggestion", lvl:6, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Миттєвий виклик", en:"Instant Summons", lvl:6, school:"прикликання", cls:["Чарівник"], cast:"1 хв", ritual:true },
    { uk:"Нестримний танець", en:"Irresistible Dance", lvl:6, school:"зачарування", cls:["Бард","Чарівник"], cast:"дія", conc:true },
    { uk:"Обернення на камінь", en:"Flesh to Stone", lvl:6, school:"перетворення", cls:["Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Передбачливість", en:"Contingency", lvl:6, school:"викликання", cls:["Чарівник"], cast:"10 хв" },
    { uk:"Перенесення крізь рослини", en:"Transport via Plants", lvl:6, school:"прикликання", cls:["Друїд"], cast:"дія" },
    { uk:"Пересування землі", en:"Move Earth", lvl:6, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Планарний союзник", en:"Planar Ally", lvl:6, school:"прикликання", cls:["Клірик"], cast:"10 хв" },
    { uk:"Пошук шляху", en:"Find the Path", lvl:6, school:"віщування", cls:["Бард","Клірик","Друїд"], cast:"1 хв", conc:true },
    { uk:"Прикликання феї", en:"Conjure Fey", lvl:6, school:"прикликання", cls:["Друїд","Чорнокнижник"], cast:"1 хв", conc:true },
    { uk:"Розпад", en:"Disintegrate", lvl:6, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Слово повернення", en:"Word of Recall", lvl:6, school:"прикликання", cls:["Клірик"], cast:"дія" },
    { uk:"Сонячний промінь", en:"Sunbeam", lvl:6, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Створення нежиті", en:"Create Undead", lvl:6, school:"некромантія", cls:["Клірик","Чорнокнижник","Чарівник"], cast:"1 хв" },
    { uk:"Стіна тернів", en:"Wall of Thorns", lvl:6, school:"прикликання", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Сфера невразливості", en:"Globe of Invulnerability", lvl:6, school:"ограждення", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Чарівний глек", en:"Magic Jar", lvl:6, school:"некромантія", cls:["Чарівник"], cast:"1 хв" },
    // --- 7 рівень ---
    { uk:"Божественне слово", en:"Divine Word", lvl:7, school:"викликання", cls:["Клірик"], cast:"бонусна дія" },
    { uk:"Вогняна куля сповільненої дії", en:"Delayed Blast Fireball", lvl:7, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Вогняний шторм", en:"Fire Storm", lvl:7, school:"викликання", cls:["Клірик","Друїд","Чаклун"], cast:"дія" },
    { uk:"Воскресіння", en:"Resurrection", lvl:7, school:"некромантія", cls:["Бард","Клірик"], cast:"1 год" },
    { uk:"Ефірність", en:"Etherealness", lvl:7, school:"перетворення", cls:["Бард","Клірик","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Зворотна гравітація", en:"Reverse Gravity", lvl:7, school:"перетворення", cls:["Друїд","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Зміна плану", en:"Plane Shift", lvl:7, school:"прикликання", cls:["Клірик","Друїд","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Магічний меч", en:"Arcane Sword", lvl:7, school:"викликання", cls:["Бард","Чарівник"], cast:"дія", conc:true },
    { uk:"Магічний міраж", en:"Mirage Arcane", lvl:7, school:"ілюзії", cls:["Бард","Друїд","Чарівник"], cast:"10 хв" },
    { uk:"Перст смерті", en:"Finger of Death", lvl:7, school:"некромантія", cls:["Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Призматичні бризки", en:"Prismatic Spray", lvl:7, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Прикликання небожителя", en:"Conjure Celestial", lvl:7, school:"прикликання", cls:["Клірик"], cast:"1 хв", conc:true },
    { uk:"Проєкція образу", en:"Project Image", lvl:7, school:"ілюзії", cls:["Бард","Чарівник"], cast:"дія", conc:true },
    { uk:"Регенерація", en:"Regenerate", lvl:7, school:"перетворення", cls:["Бард","Клірик","Друїд"], cast:"1 хв" },
    { uk:"Розкішний особняк", en:"Magnificent Mansion", lvl:7, school:"прикликання", cls:["Бард","Чарівник"], cast:"1 хв" },
    { uk:"Силова клітка", en:"Forcecage", lvl:7, school:"викликання", cls:["Бард","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Символ", en:"Symbol", lvl:7, school:"ограждення", cls:["Бард","Клірик","Чарівник"], cast:"1 хв" },
    { uk:"Симулякр", en:"Simulacrum", lvl:7, school:"ілюзії", cls:["Чарівник"], cast:"12 год" },
    { uk:"Телепортація", en:"Teleport", lvl:7, school:"прикликання", cls:["Бард","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Усамітнення", en:"Sequester", lvl:7, school:"перетворення", cls:["Чарівник"], cast:"дія" },
    // --- 8 рівень ---
    { uk:"Антимагічне поле", en:"Antimagic Field", lvl:8, school:"ограждення", cls:["Клірик","Чарівник"], cast:"дія", conc:true },
    { uk:"Антипатія/Симпатія", en:"Antipathy/Sympathy", lvl:8, school:"зачарування", cls:["Друїд","Чарівник"], cast:"1 год" },
    { uk:"Запальна хмара", en:"Incendiary Cloud", lvl:8, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Звірині подоби", en:"Animal Shapes", lvl:8, school:"перетворення", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Землетрус", en:"Earthquake", lvl:8, school:"викликання", cls:["Клірик","Друїд","Чаклун"], cast:"дія", conc:true },
    { uk:"Керування погодою", en:"Control Weather", lvl:8, school:"перетворення", cls:["Клірик","Друїд","Чарівник"], cast:"10 хв", conc:true },
    { uk:"Клон", en:"Clone", lvl:8, school:"некромантія", cls:["Чарівник"], cast:"1 год" },
    { uk:"Красномовність", en:"Glibness", lvl:8, school:"перетворення", cls:["Бард","Чорнокнижник"], cast:"дія" },
    { uk:"Лабіринт", en:"Maze", lvl:8, school:"прикликання", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Напівплан", en:"Demiplane", lvl:8, school:"прикликання", cls:["Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Недоумство", en:"Feeblemind", lvl:8, school:"зачарування", cls:["Бард","Друїд","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Підкорення чудовиська", en:"Dominate Monster", lvl:8, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Свята аура", en:"Holy Aura", lvl:8, school:"ограждення", cls:["Клірик"], cast:"дія", conc:true },
    { uk:"Слово сили: оглушення", en:"Power Word Stun", lvl:8, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Сонячний спалах", en:"Sunburst", lvl:8, school:"викликання", cls:["Друїд","Чаклун","Чарівник"], cast:"дія" },
    { uk:"Чистий розум", en:"Mind Blank", lvl:8, school:"ограждення", cls:["Бард","Чарівник"], cast:"дія" },
    // --- 9 рівень ---
    { uk:"Істинне воскресіння", en:"True Resurrection", lvl:9, school:"некромантія", cls:["Клірик","Друїд"], cast:"1 год" },
    { uk:"Істинне перевтілення", en:"True Polymorph", lvl:9, school:"перетворення", cls:["Бард","Чорнокнижник","Чарівник"], cast:"дія", conc:true },
    { uk:"Астральна проєкція", en:"Astral Projection", lvl:9, school:"некромантія", cls:["Клірик","Чорнокнижник","Чарівник"], cast:"1 год" },
    { uk:"Бажання", en:"Wish", lvl:9, school:"прикликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Брама", en:"Gate", lvl:9, school:"прикликання", cls:["Клірик","Чаклун","Чарівник"], cast:"дія", conc:true },
    { uk:"Буря відплати", en:"Storm of Vengeance", lvl:9, school:"прикликання", cls:["Друїд"], cast:"дія", conc:true },
    { uk:"Жахіття", en:"Weird", lvl:9, school:"ілюзії", cls:["Чарівник"], cast:"дія", conc:true },
    { uk:"Зміна подоби", en:"Shapechange", lvl:9, school:"перетворення", cls:["Друїд","Чарівник"], cast:"дія", conc:true },
    { uk:"Зупинка часу", en:"Time Stop", lvl:9, school:"перетворення", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Масове зцілення", en:"Mass Heal", lvl:9, school:"прикликання", cls:["Клірик"], cast:"дія" },
    { uk:"Метеоритний дощ", en:"Meteor Swarm", lvl:9, school:"викликання", cls:["Чаклун","Чарівник"], cast:"дія" },
    { uk:"Передбачення", en:"Foresight", lvl:9, school:"віщування", cls:["Бард","Друїд","Чорнокнижник","Чарівник"], cast:"1 хв" },
    { uk:"Призматична стіна", en:"Prismatic Wall", lvl:9, school:"ограждення", cls:["Чарівник"], cast:"дія" },
    { uk:"Слово сили: смерть", en:"Power Word Kill", lvl:9, school:"зачарування", cls:["Бард","Чаклун","Чорнокнижник","Чарівник"], cast:"дія" },
    { uk:"Ув'язнення", en:"Imprisonment", lvl:9, school:"ограждення", cls:["Чорнокнижник","Чарівник"], cast:"1 хв" },
  ];

  // Назва → закляття, для швидкого пошуку за українською назвою
  window.SPELL_BY_NAME = {};
  window.SPELLS.forEach(function (s) { window.SPELL_BY_NAME[s.uk] = s; });

  // Закляття класу певного рівня (lvl === null — усі рівні)
  window.spellsFor = function (cls, lvl) {
    return window.SPELLS.filter(function (s) {
      return s.cls.indexOf(cls) >= 0 && (lvl == null || s.lvl === lvl);
    });
  };
})();
